# Generated by Django 4.1.4 on 2023-04-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_comment_developer_follow_game_genre_like_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game", name="release_date", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="game", name="summary", field=models.TextField(null=True),
        ),
    ]
