# Generated by Django 4.2 on 2023-04-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_release_date_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(related_name='game', to='games.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='game', to='games.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='game', to='games.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(related_name='game', to='games.publisher'),
        ),
    ]
